# Generated by Django 3.2.3 on 2024-02-12 07:41

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0003_auto_20240212_0727'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='cooking_time',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1, 'Cooking_time can`t be less 1.')], verbose_name='Время приготовления'),
        ),
    ]
